auth:
  registry.hub.docker.com:
    username: DOCKERHUB_USERNAME
    password: DOCKERHUB_PASSWORD
images:
  # rook
  k8s.gcr.io/sig-storage/csi-attacher: shelwin/csi-attacher
  k8s.gcr.io/sig-storage/csi-node-driver-registrar: shelwin/csi-node-driver-registrar
  k8s.gcr.io/sig-storage/csi-provisioner: shelwin/csi-provisioner
  k8s.gcr.io/sig-storage/csi-resizer:v1.4.0: shelwin/csi-resizer
  k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1: shelwin/csi-snapshotter
  quay.io/csiaddons/k8s-sidecar: shelwin/k8s-sidecar
  quay.io/csiaddons/volumereplication-operator: shelwin/volumereplication-operator
  rook/ceph:v1.8.6: shelwin/rook.ceph
  # tools
  k8s.gcr.io/metrics-server/metrics-server: shelwin/metrics-server
  k8s.gcr.io/ingress-nginx/controller: shelwin/ingress-nginx-controller
  k8s.gcr.io/kube-state-metrics/kube-state-metrics: shelwin/kube-state-metrics
  k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner: shelwin/nfs-subdir-external-provisioner
  k8s.gcr.io/prometheus-adapter/prometheus-adapter: shelwin/prometheus-adapter
  # kubernetes
  k8s.gcr.io/kube-apiserver: shelwin/kube-apiserver
  k8s.gcr.io/kube-controller-manager: shelwin/kube-controller-manager
  k8s.gcr.io/kube-scheduler: shelwin/kube-scheduler
  k8s.gcr.io/kube-proxy: shelwin/kube-proxy
  k8s.gcr.io/pause: shelwin/pause
  k8s.gcr.io/etcd: shelwin/etcd
  coredns/coredns: shelwin/coredns
